# Generated by Django 3.2.5 on 2021-07-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('periodo_ingresso', models.CharField(max_length=6, verbose_name='Perído de Ingresso')),
                ('nota', models.IntegerField(verbose_name='Perído de Ingresso')),
                ('situacao', models.CharField(max_length=20, verbose_name='Situação')),
            ],
        ),
    ]
